### ISSUE TITLE
Error when enabling whiteboard in UIKit room

### ISSUE THREAD

**Issue by 0samaKamel** [ZEGOCLOUD/zego_uikit_prebuilt_web#3]
Enabling whiteboard in UIKit room, getting an error once adding the plugin: cannot read properties of undefined (reading 'electron')

This's happening no matter the version i use.. i have vitejs as dev server and build tool (Vue, Quasar UI, Vitejs).

Works just fine without the super board plugin.

<img width="674" alt="Screenshot 2023-04-27 at 1 10 40 PM" src="https://user-images.githubusercontent.com/89023834/234976805-4a5167f3-f4a0-46c2-981e-c713de3a552e.png">

<img width="545" alt="Screenshot 2023-04-27 at 1 04 29 PM" src="https://user-images.githubusercontent.com/89023834/234976720-b48a4336-afbe-4bbe-b227-536347e127c9.png">

<img width="525" alt="Screenshot 2023-04-27 at 1 06 07 PM" src="https://user-images.githubusercontent.com/89023834/234976744-e59e888b-72a0-4ede-b114-cb3b78331e0b.png">

**Comment by listen936** [comment]
> 

Are you packing with vite？

**Comment by listen936** [comment]
Set define in the vite config like this：
```javascript
define:{
  "process.versions":{}
}
```
