### ISSUE TITLE
property 'addPlugins' does not exist on type 'ZegoUIKitPrebuilt'.

### ISSUE THREAD

**Issue by caedencode** [ZEGOCLOUD/zego_uikit_prebuilt_web#4]
Anyone know how to fix this? 
zp.addPlugins({ZegoSuperBoardManager});  Gives the error property 'addPlugins' does not exist on type 'ZegoUIKitPrebuilt'.

**Comment by listen936** [comment]
> Anyone know how to fix this? zp.addPlugins({ZegoSuperBoardManager}); Gives the error property 'addPlugins' does not exist on type 'ZegoUIKitPrebuilt'.

What version are you using
